$('.owl-carousel').owlCarousel({
    loop:true,
    margin:8,
    nav:false,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:4
        },
        1000:{
            items:5
        }
    }
})